---
version: "2.4"

services:
  celery_w1:
    build: .
    restart: "on-failure"
    environment:
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=NMaqUYnKmRLZCCqL3b3A3Tjs
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_VHOST=monitor
      - RABBITMQ_WORKER_NAME=worker1
      - CELERY_RESULT_BACKEND=redis://redis:6379
    networks:
      - app-tier
    entrypoint: celery -A proj worker -l debug -n worker1@%h
  celery_w2:
    extends: celery_w1
    environment:
      - RABBITMQ_WORKER_NAME=worker2
    entrypoint: celery -A proj worker -l debug -n worker2@%h
  celery_w3:
    extends: celery_w1
    environment:
      - RABBITMQ_WORKER_NAME=worker3
    entrypoint: celery -A proj worker -l debug -n worker3@%h
  celery_w4:
    extends: celery_w1
    environment:
      - RABBITMQ_WORKER_NAME=worker4
    entrypoint: celery -A proj worker -l debug -n worker4@%h
  flower_app:
    extends: celery_w1
    depends_on:
      - celery_w1
    environment:
      - FLOWER_USERNAME=sd2e
      - FLOWER_PASSWORD=zxxnVNVLP8SCqcBkVY8pBawNkCeUFrBb
    networks:
      - app-tier
    ports:
      - "5555:5555"
    entrypoint: celery -A proj flower -l info --basic_auth=sd2e:zxxnVNVLP8SCqcBkVY8pBawNkCeUFrBb
    healthcheck:
      test: curl --fail -s http://sd2e:zxxnVNVLP8SCqcBkVY8pBawNkCeUFrBb@localhost:5555/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=NMaqUYnKmRLZCCqL3b3A3Tjs
      - RABBITMQ_DEFAULT_VHOST=monitor
    ports:
      # The rabbitMQ management plugin - running on http://localhost:15672
      - "15672:15672"
      - "5672:5672"
    networks:
      - app-tier
  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-tier
networks:
  app-tier:
    driver: bridge
